on:
  push: 
    branches:
      - main 

permissions:
  contents: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: clean deployment
        uses: strumwolf/delete-deployment-environment@v2
        with:
          token: ${{ secrets.TOKEN }}
          environment: github-pages
          onlyRemoveDeployments: true